name: "Swift Doc"
description: "Generates documentation for your Swift project"

inputs:
  inputs:
    description: "A path to a directory containing Swift (`.swift`) files in your workspace"
    required: true
    default: "./Sources"
  module-name:
    description: "The name of the module"
    required: true
  format:
    description: "The output format (commonmark or html)"
    default: "commonmark"
  output:
    description: "The path for generated output"
    required: true
    default: "./.build/documentation"
  excluded-symbols:
    description: "File containing a list of symbols to exclude from the generated documenttion"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    [
      generate,
      "${{ inputs.inputs }}",
      --format,
      "${{ inputs.format }}",
      --module-name,
      "${{ inputs.module-name }}",
      --output,
      "${{ inputs.output }}",
      --excluded-symbols,
      "${{ inputs.excluded-symbols }}",
    ]

branding:
  icon: "book"
  color: "orange"
