name: Deploy

on:
  release:
    types:
      - created

jobs:
  macos:
    name: Upload macOS Catalina release binary
    runs-on: macos-10.15

    strategy:
      matrix:
        xcode:
          - "12" # Swift 5.3

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: Build and Package
        run: |
          make swift-doc
          tar -cf swift-doc-${{ github.event.release.tag_name }}.catalina.bottle.tar swift-doc
          gzip -f swift-doc-${{ github.event.release.tag_name }}.catalina.bottle.tar
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
      - name: Upload
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./swift-doc
          asset_name: swift-doc-${{ github.event.release.tag_name }}.catalina.bottle.tar.gz
          asset_content_type: application/gzip

  linux:
    name: Upload Linux release binary

    runs-on: ubuntu-latest

    strategy:
      matrix:
        swift: ["5.3"]

    container:
      image: swift:${{ matrix.swift }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: Install System Dependencies
        run: |
          apt-get update
          apt-get install -y libxml2-dev graphviz
      - name: Build and Package
        run: |
          make swift-doc
          tar -cf swift-doc-${{ github.event.release.tag_name }}.linux.bottle.tar.gz swift-doc
          gzip -f swift-doc-${{ github.event.release.tag_name }}.linux.bottle.tar.gz
      - name: Upload
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./swift-doc
          asset_name: swift-doc-${{ github.event.release.tag_name }}.linux.bottle.tar.gz
          asset_content_type: application/gzip

  homebrew:
    name: Update Homebrew formula
    runs-on: ubuntu-latest
    needs: [macos, linux]
    steps:
      - uses: SwiftDocOrg/update-homebrew-formula-action@main
        with:
          repository: SwiftDocOrg/swift-doc
          tap: SwiftDocOrg/homebrew-formulae
          formula: Formula/swift-doc.rb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    name: Build and push Docker container

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            swiftdoc/swift-doc:latest
            swiftdoc/swift-doc:${{ github.event.release.tag_name }}
